# Generated by Django 4.1.3 on 2023-08-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_album_friend_post_remove_user_data_delete_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
