# Generated by Django 4.1.3 on 2023-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_post_type_statusupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('R', 'Regular Post'), ('SU', 'Status Update')], default='R', max_length=2),
        ),
    ]
