# Generated by Django 4.2.4 on 2023-08-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_photo_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="../media/profile_pics/test_profile.png",
                upload_to="profile_pics/",
            ),
        ),
    ]
