# Generated by Django 4.2.4 on 2023-08-25 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pics/"),
        ),
    ]
