# Generated by Django 4.2.4 on 2023-08-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_photo_user_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="album_photos/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile_pics/test_profile.png",
                upload_to="profile_pics/",
            ),
        ),
    ]
