# Generated by Django 4.2.4 on 2023-08-27 16:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to=users.models.userPicsDir),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=users.models.userPhotoDir),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="images/default_pic.jpeg",
                upload_to=users.models.userPicsDir,
            ),
        ),
    ]
