# Generated by Django 4.2.4 on 2023-09-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_user_thumbnail_alter_photo_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendshiprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="sent",
                max_length=32,
            ),
        ),
    ]
