# Generated by Django 4.2.4 on 2023-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_friendshiprequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendshiprequest",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
