# Generated by Django 4.2.4 on 2023-09-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_photo_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.album",
            ),
        ),
    ]
